export const DashboardData = [
  {
    id: "N001",
    name: "Moderate/Severe Pain [Short Stay]",
    type: "Short Stay",
    q1Avg: 0,
    q2Avg: 0,
    q3Avg: 0,
    stateAvg: 3.08,
    nationalAvg: 2.1,
    category: "Patient Experience",
  },
  {
    id: "N002",
    name: "New/Worsened Pressure Ulcers [Short Stay, NHC]",
    type: "Short Stay",
    q1Avg: 1.94,
    q2Avg: 1.85,
    q3Avg: 0,
    stateAvg: 1.3,
    nationalAvg: 0.81,
    category: "Quality",
  },
  {
    id: "N003",
    name: "Influenza Vaccine Appropriately Given [Short Stay, NHC]",
    type: "Short Stay",
    q1Avg: 93.2,
    q2Avg: 93.2,
    q3Avg: 93.2,
    stateAvg: 70.75,
    nationalAvg: 77.04,
    category: "Quality",
  },
  {
    id: "N004",
    name: "Received Influenza Vaccine [Short Stay]",
    type: "Short Stay",
    q1Avg: 34.4,
    q2Avg: 34.4,
    q3Avg: 34.4,
    stateAvg: 49.37,
    nationalAvg: 41.79,
    category: "Quality",
  },
  {
    id: "N005",
    name: "Declined Influenza Vaccine [Short Stay]",
    type: "Short Stay",
    q1Avg: 58.8,
    q2Avg: 58.8,
    q3Avg: 58.8,
    stateAvg: 31.34,
    nationalAvg: 38.81,
    category: "Quality",
  },
  {
    id: "N006",
    name: "Influenza Vaccine Contraindication [Short Stay]",
    type: "Short Stay",
    q1Avg: 0,
    q2Avg: 0,
    q3Avg: 0,
    stateAvg: 1.73,
    nationalAvg: 1.38,
    category: "Quality",
  },
  {
    id: "N007",
    name: "Pneumococcal Vaccine Appropriately Given [Short Stay, NHC]",
    type: "Short Stay",
    q1Avg: 100,
    q2Avg: 100,
    q3Avg: 100,
    stateAvg: 75.12,
    nationalAvg: 80.65,
    category: "Quality",
  },
  {
    id: "N008",
    name: "Received Pneumococcal Vaccine [Short Stay]",
    type: "Short Stay",
    q1Avg: 16.18,
    q2Avg: 19.27,
    q3Avg: 20,
    stateAvg: 45.02,
    nationalAvg: 40.03,
    category: "Quality",
  },
  {
    id: "N009",
    name: "Declined Pneumococcal Vaccine [Short Stay]",
    type: "Short Stay",
    q1Avg: 83.4,
    q2Avg: 80.21,
    q3Avg: 80,
    stateAvg: 39.62,
    nationalAvg: 42.7,
    category: "Quality",
  },
  {
    id: "N010",
    name: "Pneumococcal Vaccine Contraindication [Short Stay]",
    type: "Short Stay",
    q1Avg: 0.41,
    q2Avg: 0.52,
    q3Avg: 0,
    stateAvg: 3.12,
    nationalAvg: 2.28,
    category: "Quality",
  },
  {
    id: "N011",
    name: "Newly Received Antipsychotic [Short Stay, NHC, Five Star]",
    type: "Short Stay",
    q1Avg: 0,
    q2Avg: 1.49,
    q3Avg: 3.39,
    stateAvg: 1.95,
    nationalAvg: 1.71,
    category: "Quality",
  },
  {
    id: "N013",
    name: "1+ Falls with Major Injury [Short Stay, NHC, Five Star, Composite]",
    type: "Short Stay",
    q1Avg: 4,
    q2Avg: 4.29,
    q3Avg: 2.22,
    stateAvg: 4.5,
    nationalAvg: 3.35,
    category: "Return To Acute",
  },
  {
    id: "N013",
    name: "1+ Falls with Major Injury [Short Stay, NHC, Five Star, Composite]",
    type: "Short Stay",
    q1Avg: 4,
    q2Avg: 4.29,
    q3Avg: 2.22,
    stateAvg: 4.5,
    nationalAvg: 3.35,
    category: "Patient Experience",
  },
  {
    id: "N014",
    name: "Moderate/Severe Pain [Long Stay]",
    type: "Long Stay",
    q1Avg: 0,
    q2Avg: 0,
    q3Avg: 0,
    stateAvg: 1.82,
    nationalAvg: 0.93,
    category: "Patient Experience",
  },
  {
    id: "N015",
    name: "High-Risk Pressure Ulcers [Short Stay, NHC, Five Star, Composite, v18 Freeze]",
    type: "Short Stay",
    q1Avg: 0,
    q2Avg: 0,
    q3Avg: 0,
    stateAvg: 6.06,
    nationalAvg: 2.86,
    category: "Quality",
  },
  {
    id: "N016",
    name: "Influenza Vaccine Appropriately Given [Long Stay, NHC, Composite]",
    type: "Long Stay",
    q1Avg: 100,
    q2Avg: 100,
    q3Avg: 100,
    stateAvg: 94.55,
    nationalAvg: 94.86,
    category: "Quality",
  },
  {
    id: "N017",
    name: "Received Influenza Vaccine [Long Stay]",
    type: "Long Stay",
    q1Avg: 69.14,
    q2Avg: 69.14,
    q3Avg: 69.14,
    stateAvg: 72.08,
    nationalAvg: 71.86,
    category: "Quality",
  },
  {
    id: "N018",
    name: "Declined Influenza Vaccine [Long Stay]",
    type: "Long Stay",
    q1Avg: 29.63,
    q2Avg: 29.63,
    q3Avg: 29.63,
    stateAvg: 21.49,
    nationalAvg: 22.41,
    category: "Quality",
  },
  {
    id: "N019",
    name: "Influenza Vaccine Contraindication [Long Stay]",
    type: "Long Stay",
    q1Avg: 1.23,
    q2Avg: 1.23,
    q3Avg: 1.23,
    stateAvg: 0.86,
    nationalAvg: 0.7,
    category: "Quality",
  },
  {
    id: "N020",
    name: "Pneumococcal Vaccine Appropriately Given [Long Stay, NHC, Composite]",
    type: "Long Stay",
    q1Avg: 100,
    q2Avg: 100,
    q3Avg: 100,
    stateAvg: 90.95,
    nationalAvg: 92.64,
    category: "Quality",
  },
  {
    id: "N021",
    name: "Received Pneumococcal Vaccine [Long Stay]",
    type: "Long Stay",
    q1Avg: 46.67,
    q2Avg: 42.86,
    q3Avg: 51.11,
    stateAvg: 60.24,
    nationalAvg: 61.48,
    category: "Quality",
  },
  {
    id: "N022",
    name: "Declined Pneumococcal Vaccine [Long Stay]",
    type: "Long Stay",
    q1Avg: 52,
    q2Avg: 57.14,
    q3Avg: 48.89,
    stateAvg: 30.67,
    nationalAvg: 29.49,
    category: "Quality",
  },
  {
    id: "N023",
    name: "Pneumococcal Vaccine Contraindication [Long Stay]",
    type: "Long Stay",
    q1Avg: 1.33,
    q2Avg: 0,
    q3Avg: 0,
    stateAvg: 3.09,
    nationalAvg: 1.71,
    category: "Quality",
  },
  {
    id: "N024",
    name: "Urinary Tract Infection [Long Stay, NHC, Five Star, Composite]",
    type: "Long Stay",
    q1Avg: 2.74,
    q2Avg: 2.86,
    q3Avg: 2.27,
    stateAvg: 3.46,
    nationalAvg: 2.06,
    category: "Quality",
  },
  {
    id: "N025",
    name: "Loss of Bowel/Bladder Control [Long Stay, NHC, Composite]",
    type: "Long Stay",
    q1Avg: 0,
    q2Avg: 0,
    q3Avg: 0,
    stateAvg: 36.82,
    nationalAvg: 48.56,
    category: "Quality",
  },
  {
    id: "N026",
    name: "Catheter Left in Bladder [Long Stay, NHC, Five Star, Composite]",
    type: "Long Stay",
    q1Avg: 0,
    q2Avg: 0,
    q3Avg: 0,
    stateAvg: 2.14,
    nationalAvg: 1.24,
    category: "Quality",
  },
  {
    id: "N027",
    name: "Physically Restrained [Long Stay, NHC, Composite]",
    type: "Long Stay",
    q1Avg: 0,
    q2Avg: 0,
    q3Avg: 0,
    stateAvg: 0.14,
    nationalAvg: 0.14,
    category: "Quality",
  },
  {
    id: "N028",
    name: "Help with ADLs Increased [Long Stay, NHC, Five Star, Composite, v18 Freeze]",
    type: "Long Stay",
    q1Avg: 3.92,
    q2Avg: 4,
    q3Avg: 21.88,
    stateAvg: 13.59,
    nationalAvg: 14.13,
    category: "Quality",
  },
  {
    id: "N029",
    name: "Lost Too Much Weight [Long Stay, NHC, Composite]",
    type: "Long Stay",
    q1Avg: 6,
    q2Avg: 5.88,
    q3Avg: 0,
    stateAvg: 4.08,
    nationalAvg: 5.85,
    category: "Quality",
  },
  {
    id: "N030",
    name: "Depressive Symptoms [Long Stay, NHC, Composite]",
    type: "Long Stay",
    q1Avg: 0,
    q2Avg: 0,
    q3Avg: 0,
    stateAvg: 4,
    nationalAvg: 9.01,
    category: "Quality",
  },
  {
    id: "N031",
    name: "Received Antipsychotic Medication [Long Stay, NHC, Five Star, Composite]",
    type: "Long Stay",
    q1Avg: 7.35,
    q2Avg: 7.58,
    q3Avg: 6.98,
    stateAvg: 14.83,
    nationalAvg: 14.69,
    category: "Quality",
  },
  {
    id: "N032",
    name: "Prevalence of Falls [Long Stay]",
    type: "Long Stay",
    q1Avg: 64,
    q2Avg: 62.86,
    q3Avg: 66.67,
    stateAvg: 48.45,
    nationalAvg: 41.7,
    category: "Quality",
  },
  {
    id: "N033",
    name: "Prevalence of Antianxiety/Hypnotic Use [Long Stay]",
    type: "Long Stay",
    q1Avg: 18.6,
    q2Avg: 26.19,
    q3Avg: 16.13,
    stateAvg: 11.05,
    nationalAvg: 6.034,
    category: "Quality",
  },
  {
    id: "N034",
    name: "Behavior Symptoms Affecting Others [Long Stay]",
    type: "Long Stay",
    q1Avg: 5.71,
    q2Avg: 5.26,
    q3Avg: 2.44,
    stateAvg: 15.09,
    nationalAvg: 15.38,
    category: "Quality",
  },
  {
    id: "N035",
    name: "Walking/Locomotion Independently Worsened [Long Stay, NHC, Five Star, v18 Freeze]",
    type: "Long Stay",
    q1Avg: 23.5,
    q2Avg: 7.85,
    q3Avg: 17.36,
    stateAvg: 13.41,
    nationalAvg: 15.34,
    category: "Quality",
  },
  {
    id: "N036",
    name: "Used Antianxiety or Hypnotic Medication [Long Stay, NHC]",
    type: "Long Stay",
    q1Avg: 30.77,
    q2Avg: 31.37,
    q3Avg: 25,
    stateAvg: 25.33,
    nationalAvg: 19.69,
    category: "Quality",
  },
  {
    id: "N037",
    name: "Improvements in Function [Short Stay, NHC, Five Star, v18 Freeze]",
    type: "Short Stay",
    q1Avg: 0,
    q2Avg: 0,
    q3Avg: 0,
    stateAvg: 78.06,
    nationalAvg: 76.76,
    category: "Quality",
  },
  {
    id: "N045",
    name: "Pressure Ulcers [Long Stay, Five Star]",
    type: "Long Stay",
    q1Avg: 9.59,
    q2Avg: 10,
    q3Avg: 9.09,
    stateAvg: 5.97,
    nationalAvg: 6.33,
    category: "Quality",
  },
  {
    id: "N046",
    name: "New/Worsened Bowel or Bladder [Long Stay]",
    type: "Long Stay",
    q1Avg: 15.38,
    q2Avg: 14.06,
    q3Avg: 9.52,
    stateAvg: 18.44,
    nationalAvg: 21.2,
    category: "Quality",
  },
  {
    id: "S001",
    name: "Functional Assessment/Care Plan [QRP, Short Stay]",
    type: "Short Stay",
    q1Avg: 100,
    q2Avg: 100,
    q3Avg: 100,
    stateAvg: 98.63,
    nationalAvg: 99.3,
    category: "Quality",
  },
  {
    id: "S002",
    name: "SNF Stays New/Worsened Pressure Ulcers [QRP, Short Stay]",
    type: "Short Stay",
    q1Avg: 0,
    q2Avg: 0,
    q3Avg: 0,
    stateAvg: 1.73,
    nationalAvg: 1.3,
    category: "Quality",
  },
  {
    id: "S003",
    name: "Potentially Preventable Readmission for SNF QRP [Claims, QRP, Short Stay]",
    type: "Short Stay",
    q1Avg: 76.32,
    q2Avg: 60,
    q3Avg: 95.35,
    stateAvg: 94.91,
    nationalAvg: 93.8,
    category: "Quality",
  },
  {
    id: "S004",
    name: "Drug Regimen Review [QRP, Short Stay]",
    type: "Short Stay",
    q1Avg: 11.48,
    q2Avg: 11.48,
    q3Avg: 11.48,
    stateAvg: 0,
    nationalAvg: 0,
    category: "Quality",
  },
  {
    id: "S013",
    name: "Falls with Major Injury [QRP, Short Stay]",
    type: "Short Stay",
    q1Avg: 0,
    q2Avg: 3.33,
    q3Avg: 0,
    stateAvg: 1.42,
    nationalAvg: 0.8,
    category: "Quality",
  },
  {
    id: "S024",
    name: "Discharge of Self-Care Score [Short Stay, NHC, QRP]",
    type: "Short Stay",
    q1Avg: 47.62,
    q2Avg: 61.54,
    q3Avg: 22.73,
    stateAvg: 61.02,
    nationalAvg: 52.6,
    category: "Quality",
  },
  {
    id: "S025",
    name: "Discharge Mobility Score [Short Stay, NHC, QRP]",
    type: "Short Stay",
    q1Avg: 42.86,
    q2Avg: 69.23,
    q3Avg: 31.82,
    stateAvg: 43.39,
    nationalAvg: 26.98,
    category: "Quality",
  },
  {
    id: "S038",
    name: "SNF Stays Changes Pressure Ulcers/Injury [Short Stay, NHC, Five Star]",
    type: "Short Stay",
    q1Avg: 0,
    q2Avg: 0,
    q3Avg: 0,
    stateAvg: 2.65,
    nationalAvg: 2.4,
    category: "Quality",
  },
  {
    id: "S039",
    name: "Healthcare-Associated Infections (HAI) Requiring Hospitalization [Claims, QRP, Short Stay]",
    type: "Short Stay",
    q1Avg: 5.16,
    q2Avg: 5.16,
    q3Avg: 5.16,
    stateAvg: 0,
    nationalAvg: 0,
    category: "Quality",
  },
  {
    id: "S042",
    name: "Expected Discharge Score [QRP, Short Stay]",
    type: "Short Stay",
    q1Avg: 47.62,
    q2Avg: 76.92,
    q3Avg: 31.82,
    stateAvg: 54.85,
    nationalAvg: 53.91,
    category: "Length of Stay",
  },
  {
    id: "S042",
    name: "Expected Discharge Score [QRP, Short Stay]",
    type: "Short Stay",
    q1Avg: 47.62,
    q2Avg: 76.92,
    q3Avg: 31.82,
    stateAvg: 54.85,
    nationalAvg: 53.91,
    category: "Patient Experience",
  },
  {
    id: "C521",
    name: "Re-Hospitalized After SNF Admission [Claims, Short Stay, NHC, Five Star]",
    type: "Short Stay",
    q1Avg: 25.08,
    q2Avg: 25.08,
    q3Avg: 25.08,
    stateAvg: 22.94,
    nationalAvg: 21.47,
    category: "Return To Acute",
  },
  {
    id: "C522",
    name: "Outpatient ER Visit [Claims, Short Stay, NHC, Five Star]",
    type: "Short Stay",
    q1Avg: 15.39,
    q2Avg: 15.39,
    q3Avg: 15.39,
    stateAvg: 16.26,
    nationalAvg: 11.59,
    category: "Quality",
  },
  {
    id: "C523",
    name: "Discharged to Community [Claims, Short Stay, NHC, Five Star]",
    type: "Short Stay",
    q1Avg: 53.93,
    q2Avg: 53.93,
    q3Avg: 53.93,
    stateAvg: 0,
    nationalAvg: 49.74,
    category: "Quality",
  },
  {
    id: "C551",
    name: "Number of Hospitalizations [Claims, Long Stay, Five Star]",
    type: "Long Stay",
    q1Avg: 1,
    q2Avg: 1,
    q3Avg: 1,
    stateAvg: 2.06,
    nationalAvg: 1.65,
    category: "Quality",
  },
  {
    id: "C522",
    name: "Outpatient ER Visit [Claims, Long Stay, Five Star]",
    type: "Long Stay",
    q1Avg: 3.55,
    q2Avg: 3.55,
    q3Avg: 3.55,
    stateAvg: 2.64,
    nationalAvg: 1.65,
    category: "Quality",
  },
];

export const MoreInfo = {
  patientExperience: [
    "N001 - Moderate/Severe Pain [Short Stay]",
    "N013 - 1+ Falls with Major Injury [Short Stay]",
    "N014 - Moderate/Severe Pain [Long Stay]",
    "S042 - Expected Discharge Score [Short Stay]",
  ],
  quality: [
    "N002 - New/Worsened Pressure Ulcers [Short Stay]",
    "N003 - Influenza Vaccine Appropriately Given [Short Stay]",
    "N004 - Received Influenza Vaccine [Short Stay]",
    "N005 - Declined Influenza Vaccine [Short Stay]",
    "N006 - Influenza Vaccine Contraindication [Short Stay]",
    "N007 - Pneumococcal Vaccine Appropriately Given [Short Stay]",
    "N008 - Received Pneumococcal Vaccine [Short Stay]",
    "N009 - Declined Pneumococcal Vaccine [Short Stay]",
    "N010 - Pneumococcal Vaccine Contraindication [Short Stay]",
    "N011 - Newly Received Antipsychotic [Short Stay]",
    "N015 - High-Risk Pressure Ulcers [Short Stay]",
    "N016 - Influenza Vaccine Appropriately Given [Long Stay]",
    "N017 - Received Influenza Vaccine [Long Stay]",
    "N018 - Declined Influenza Vaccine [Long Stay]",
    "N019 - Influenza Vaccine Contraindication [Long Stay]",
    "N020 - Pneumococcal Vaccine Appropriately Given [Long Stay]",
    "N021 - Received Pneumococcal Vaccine [Long Stay]",
    "N022 - Declined Pneumococcal Vaccine [Long Stay]",
    "N023 - Pneumococcal Vaccine Contraindication [Long Stay]",
    "N024 - Urinary Tract Infection [Long Stay]",
    "N025 - Loss of Bowel/Bladder Control [Long Stay]",
  ],
  returnToAcute: [
    "N013 - 1+ Falls with Major Injury [Short Stay]",
    "C521 - Re-Hospitalized After SNF Admission [Short Stay]",
  ],
  lengthOfStay: ["S042 - Expected Discharge Score [Short Stay]"],
};
